### ISSUE TITLE
herokuデプロイは完了しているが、webpackエラーが本番環境に起きている

### ISSUE THREAD

**Issue by reiji820** [reiji820/planet#27]

**Comment by reiji820** [comment]
webpacker.ymlのcompileをtrueにしても解決できず

**Comment by reiji820** [comment]
heroku側でbuildパックを設定したが解決せず

**Comment by reiji820** [comment]
開発環境では問題なく動作できている
以下、heroku run rails webpacker:compile時のエラー
```
MacBook-Pro:planet ogurareijiro$ heroku run rails webpacker:compile
Running rails webpacker:compile on ⬢ planet... up, run.1574 (Basic)
Compiling...
Compilation failed:
[webpack-cli] TypeError: Cannot read properties of undefined (reading 'getArguments')
    at WebpackCLI.getBuiltInOptions (/app/node_modules/webpack-cli/lib/webpack-cli.js:831:77)
    at makeCommand.options.entry (/app/node_modules/webpack-cli/lib/webpack-cli.js:939:33)
    at async WebpackCLI.makeCommand (/app/node_modules/webpack-cli/lib/webpack-cli.js:443:31)
    at async loadCommandByName (/app/node_modules/webpack-cli/lib/webpack-cli.js:937:17)
    at async Command.<anonymous> (/app/node_modules/webpack-cli/lib/webpack-cli.js:1336:17)
    at async Command.parseAsync (/app/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async WebpackCLI.run (/app/node_modules/webpack-cli/lib/webpack-cli.js:1360:9)
    at async runCLI (/app/node_modules/webpack-cli/lib/bootstrap.js:9:9)
```

**Comment by reiji820** [comment]
webpackのバージョンをpackage.jsonで変更したらいけた！！
